# Generated by Django 5.2.5 on 2025-08-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyreport',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
