# Generated by Django 5.2.5 on 2025-08-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_dummyreport_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dummyreport',
            name='price',
        ),
    ]
