# Generated by Django 5.2.5 on 2025-08-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_dummyreport_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyreport',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
