# Generated by Django 5.2.5 on 2025-08-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_dummyreport_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('value', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='DummyReport',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='date2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='value',
            new_name='value2',
        ),
    ]
